#!/bin/bash

DURATION="20"
PORT1="5201"
PORT2="5202"
PORT3="5203"
PORT4="5204"
#docker exec -t oai-upf-slice12 "apt update; apt install -y iputils-ping iperf3"

docker exec -t oai-ext-dn /usr/bin/killall iperf3 2>/dev/null

docker exec -t oai-ext-dn /usr/bin/nohup /usr/bin/iperf3 -B 192.168.70.145 -p $PORT1 -s >/dev/null 2>&1 &
docker exec -t oai-ext-dn /usr/bin/nohup /usr/bin/iperf3 -B 192.168.70.145 -p $PORT2 -s >/dev/null 2>&1 &
docker exec -t oai-ext-dn /usr/bin/nohup /usr/bin/iperf3 -B 192.168.70.145 -p $PORT3 -s >/dev/null 2>&1 &
docker exec -t oai-ext-dn /usr/bin/nohup /usr/bin/iperf3 -B 192.168.70.145 -p $PORT4 -s >/dev/null 2>&1 &

sleep 2
echo "check that all iperf servers are running"
docker exec -t oai-ext-dn pgrep iperf3

echo "performing uplink tests for ${DURATION}s"
docker exec -t rfsim5g-oai-nr-ue1 /usr/bin/iperf3 -B 12.2.1.2 -p $PORT1 -c 192.168.70.145 -t $DURATION > /tmp/oai/slicing-with-nssf/iperf-client-ue1.txt 2>&1 &
docker exec -t rfsim5g-oai-nr-ue2 /usr/bin/iperf3 -B 12.2.1.3 -p $PORT2 -c 192.168.70.145 -t $DURATION > /tmp/oai/slicing-with-nssf/iperf-client-ue2.txt 2>&1 &
docker exec -t rfsim5g-oai-nr-ue3 /usr/bin/iperf3 -B 12.1.1.2 -p $PORT3 -c 192.168.70.145 -t $DURATION > /tmp/oai/slicing-with-nssf/iperf-client-ue3.txt 2>&1 &
docker exec -t rfsim5g-oai-nr-ue4 /usr/bin/iperf3 -B 12.1.1.3 -p $PORT4 -c 192.168.70.145 -t $DURATION > /tmp/oai/slicing-with-nssf/iperf-client-ue4.txt 2>&1
sleep 5
echo "performing downlink tests for ${DURATION}s"
docker exec -t rfsim5g-oai-nr-ue1 /usr/bin/iperf3 -R -B 12.2.1.2 -p $PORT1 -c 192.168.70.145 -t $DURATION >> /tmp/oai/slicing-with-nssf/iperf-client-ue1.txt 2>&1 &
docker exec -t rfsim5g-oai-nr-ue2 /usr/bin/iperf3 -R -B 12.2.1.3 -p $PORT2 -c 192.168.70.145 -t $DURATION >> /tmp/oai/slicing-with-nssf/iperf-client-ue2.txt 2>&1 &
docker exec -t rfsim5g-oai-nr-ue3 /usr/bin/iperf3 -R -B 12.1.1.2 -p $PORT3 -c 192.168.70.145 -t $DURATION >> /tmp/oai/slicing-with-nssf/iperf-client-ue3.txt 2>&1 &
docker exec -t rfsim5g-oai-nr-ue4 /usr/bin/iperf3 -R -B 12.1.1.3 -p $PORT4 -c 192.168.70.145 -t $DURATION >> /tmp/oai/slicing-with-nssf/iperf-client-ue4.txt 2>&1
sleep 5
ls -l /tmp/oai/slicing-with-nssf/*
cat /tmp/oai/slicing-with-nssf/*
